jobs:
  backup-postgres-dev:
    database:
      type: "postgres"
      host: "db"
      user: "postgres"
      password: "postgres"
      port: 5432
    s3:
      prefix: "prefix"
      bucket: "storage"
      key: ""
      secret: ""
      storage_class: "ONEZONE_IA"
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 30
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
