services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: root
      POSTGRES_DB: testdata

  restore:
    build: .
    environment:
        DATABASE_USER: root
        DATABASE_PASSWORD: asdfasdf
        DATABASE_HOST: db
        DATABASE_PORT: 5432
        IS_AUDIT: "true"
        REMOVE_DATABASE: "true"
        FILE_URL: https://hodfords-backup-dev.s3.eu-west-2.amazonaws.com/postgres-dev/woty-dev/2025/02/14/woty-dev_2025-02-14_00-00-31.dump?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEBsaCWV1LXdlc3QtMiJHMEUCIAT9eEFvfw1rl%2BS%2FJpkXVMlghpeo1pOLvogb0ysjREzzAiEAvsB80qQElTauGi0OYhb%2FQteNJ2H8roVL59ywC1GXVhUqxwMIVBABGgw0ODk3MjY0OTEwMDQiDLd2X6Jy%2BzH6tBJ8WCqkA%2B02sKMUdmkc6MhL55LiXsao8HEYY2nZcIaeso2GYuwUZoKBLcc5z79NKcUWUVf3cU3sKQbJWi1sFMYIyCduPmPl4eS%2BfCJBfsqBc4D2GdsorVP6fUa1U5z29lyHAeMb93%2Fdk2V5SUuVANg4YDIQ7y1Kjm%2FKYXuGkWs64LlQSTCsp3ZF6Or1sgQisutY6BNbQKiM4BhQUU0gg58rdPkC3dqXD4VI9WPQJt9Z%2B3WWG6O9I9vf1vgzt160lEkk%2F6dr5hRCcapfrUmwvqFG2VLSXSzHI1cTHcXh2EPnVeXuvGfcoP%2FCEZ4MCJOjKuuzBiHmzCvg541b6nLdjWU3%2FT4S1ZTTpX4D%2FR5HKTsUSG4c7I5f4Yrs975JBQelwC7Y%2F4cAsFZKgymBuTRjjsKwAbIBNGvhH27MyL0X9tt6J4X6CmDkXuPVzQ4Tl%2FytywZyQbRP%2F%2F7vZBKVQj16%2FUnet3FUsm%2FcPV%2B2BDlxVYwean5ah08xwg9ZSU948hoz%2F%2Bnss%2Buy6qGXXrVW%2B5jqhnDlGgJA02Wkj2qN4pTAY53knPyIzVcMedSw7jDj9fm9BjrkAnMLiw0c49%2FB%2FFYVN9slaAedsH3HfCABFqedXIhfULHXs8v80881MGmpk%2Bf4EObjWgvMUZpdMQVLlEd8C8N8BYYPUxgY%2B%2Bhb3rWjckWxWCke0h9kUwJ%2BJKE6HiMPjZebS02xYLeLSPdBJdByt6vVNmHN%2FPOfGernb7kKovpWv%2Bn6olmREcK22yOpU9l3yBhNWDNeQ8mlyAwIFXkHEDrVjW6AH6vJ4dqvzzRYm7WSmvonIKq0jqSSmcBeSsI4zcsDzgpBvznDbo2StpvvM%2BRESsOmtNB0IEEtr%2FdqQcyhoe2cCb2pwCYYnP6cVW22IX1hCtVlhACSMUUiiHK79dXOy%2BxlzwrmF5crhTTQyXzCJrjj3BipSkdz5zw15hQDVxuB0UpL1PTMfgdLqVF5aDrpm3hd7bqoqQGP3zhPa6AuTYaijXB7UdLm6sf1czg4BUC7YdrZxeWIFbh3JaV0ENHYf9niNEsn&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAXEBPZHF6KANPEMGL%2F20250226%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20250226T022405Z&X-Amz-Expires=36000&X-Amz-SignedHeaders=host&X-Amz-Signature=1b616ffd0f5e69d5e43545d1b99e13aaf25b48b2c8b8e0e7880f90803ad57f7d
