services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: root
      POSTGRES_DB: testdata

  restore:
    build: .
    environment:
        DATABASE_USER: root
        DATABASE_PASSWORD: asdfasdf
        DATABASE_HOST: db
        DATABASE_PORT: 5432
        IS_AUDIT: "true"
        REMOVE_DATABASE: "true"
        FILE_URL: "https://storage.s3.amazonaws.com/backup/backup.dump"
