{{- range $jobname, $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjobs.releaseName" $ }}-{{ $jobname }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Allow" }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit | default 10 }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "cronjobs.releaseName" $ }}
            cron: {{ $jobname }}
        spec:
        {{- if and (hasKey $job "serviceAccount") (hasKey $job.serviceAccount "name") }}
          serviceAccountName: {{ $job.serviceAccount.name }}
        {{- else }}
          serviceAccountName: {{ $.Release.Name}}-{{ $jobname }}
        {{- end }}
        {{- if hasKey $job "securityContext" }}
          {{- if $job.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ $job.securityContext.runAsUser }}
            {{- if $job.securityContext.runAsGroup }}
            runAsGroup: {{ $job.securityContext.runAsGroup }}
            {{- end }}
            {{- if $job.securityContext.fsGroup }}
            fsGroup: {{ $job.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          containers:
          - name: {{ $jobname }}
            {{- if eq $job.database.type "postgres" }}
            image: clownfishx/baka-postgres:0.0.2
            {{- else }}
            image: clownfishx/baka-mongo:0.0.3
            {{- end }}
            imagePullPolicy: IfNotPresent
            env:
            - name: "BUCKET_PREFIX"
              value: {{ $job.s3.prefix| quote  }}
            - name: "AWS_BUCKET"
              value: {{ $job.s3.bucket | quote }}
            - name: "AWS_ACCESS_KEY_ID"
              value: {{ $job.s3.key | quote }}
            - name: "AWS_SECRET_ACCESS_KEY"
              value: {{ $job.s3.secret | quote }}
            {{- if eq $job.database.type "postgres" }}
            - name: "PGUSER"
              value: {{ $job.database.user | quote }}
            - name: "PGPASSWORD"
              value: {{$job.database.password | quote }}
            - name: "PGHOST"
              value: {{ $job.database.host | quote }}
            - name: "PGPORT"
              value: {{ $job.database.port | quote }}
            {{- else }}
            - name: "MONGODB_USERNAME"
              value: {{ $job.database.user| quote }}
            - name: "MONGODB_PASSWORD"
              value: {{ $job.database.password| quote }}
            - name: "MONGODB_HOST"
              value: {{ $job.database.host| quote }}
            - name: "MONGODB_PORT"
              value: {{ $job.database.port| quote }}
            {{- end }}
            {{- with $job.envFrom }}
            envFrom:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.command }}
            command:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit | default 10 }}
{{- end }}
