{{- range $jobname, $job := .Values.jobs }}
---
{{- range $v:= .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $jobname }}-{{ $v.refSecretName }}-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $jobname }}-{{ $v.refSecretName }}-secret
  data:
    {{- range $key, $value := $v.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        {{- if $v.isUseProperty }}
        key: {{ $v.refSecretName }}
        property: {{ $value }}
        {{- else }}
        key: {{ $value }}
        {{- end }}
    {{- end }}
---
{{- end }}

{{- end }}
