services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: root
      POSTGRES_DB: testdata

  backup:
    build: .
    environment:
      BUCKET_PREFIX: testing
      PGUSER: root
      PGPASSWORD: asdfasdf
      PGHOST: db
      AWS_BUCKET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      STORAGE_CLASS: ONEZONE_IA
      IGNORE_DATABASES: database_default,database_default2
