services:
  db:
    image: postgres:14.4
    environment:
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_USER: postgres
      POSTGRES_DB: testdata

  backup:
    build: .
    environment:
      BUCKET_PREFIX: testing
      DATABASE_USER: postgres
      DATABASE_PASSWORD: asdfasdf
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      AWS_BUCKET: abc
      AWS_ACCESS_KEY_ID: abc
      AWS_SECRET_ACCESS_KEY: abc
      STORAGE_CLASS: ONEZONE_IA
      IGNORE_DATABASES: database_default,database_default2
      FILE_NAME: abc
      DATABASE_NAME: testdata
