services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"

  backup:
    build: .
    environment:
      BUCKET_PREFIX: testing
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: adminpassword
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      AWS_BUCKET:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      STORAGE_CLASS: ONEZONE_IA
      IGNORE_DATABASES: database_default,database_default2
